sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
script: npm run ci
# whenever a tag is pushed, we deploy to github releases
before_deploy: npm run release
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "dist/parallax-ide.zip"
  skip_cleanup: true
  on:
    tags: true
    node: '0.10'
    all_branches: true
