sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
# https://mediocre.com/forum/topics/phantomjs-2-and-travis-ci-we-beat-our-heads-against-a-wall-so-you-dont-have-to
# we alter PATH to use PWD first to avoid the use of sudo
before_install:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - export PATH=$PWD:$PATH
script: npm run ci
# whenever a tag is pushed, we deploy to github releases
before_deploy: npm run release
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "dist/parallax-ide.zip"
  skip_cleanup: true
  on:
    tags: true
    node: '0.10'
    all_branches: true
